// swift-tools-version:5.9
import PackageDescription

// REMOTE distribution manifest — GENERATED by scripts/build-release.sh, do not hand-edit.
// It fills the binaryTarget url (the GitHub Release asset for the release tag) and the
// checksum (swift package compute-checksum HiPayFullservice.xcframework.zip).
//
// This mirrors the repository's Package.swift exactly EXCEPT the HiPayFullservice target,
// which is a *remote* binaryTarget(url:checksum:) instead of a local binaryTarget(path:).
// The two Swift products and the HiPayCard resources are unchanged.
//
// This manifest exists ONLY on release tags: the branch keeps the local one so day-to-day
// development builds against the XCFramework on disk.
let package = Package(
    name: "HiPayFullserviceKMP",
    // Required for the HiPayCard localized .strings catalogs (story 5.2);
    // a device locale with no catalog falls back to EN.
    defaultLocalization: "en",
    platforms: [.iOS(.v15)],
    products: [
        // Headless SDK: payment orchestration, no UI.
        .library(name: "HiPayCore", targets: ["HiPayCore"]),
        // Card entry UI layer on top of HiPayCore.
        .library(name: "HiPayCard", targets: ["HiPayCard"]),
    ],
    targets: [
        // KMP binary hosted as a GitHub Release asset; integrity pinned by checksum.
        .binaryTarget(
            name: "HiPayFullservice",
            url: "https://github.com/hipay/hipay-payments-sdk-ios/releases/download/1.0.0/HiPayFullservice.xcframework.zip",
            checksum: "1f7b4b4988ed3932f0b29cdcda5f02421d86409c26468ec4d2adbf8359f757cd"
        ),
        .target(
            name: "HiPayCore",
            dependencies: ["HiPayFullservice"]
        ),
        .target(
            name: "HiPayCard",
            dependencies: ["HiPayCore"],
            // Card-network brand icons (neutral + Visa/MC/Amex/Maestro/BCMC/CB),
            // loaded via Image(_:bundle: .module).
            resources: [.process("Resources")]
        ),
    ]
)
