// swift-tools-version:5.9
import PackageDescription

// REMOTE distribution manifest — GENERATED by scripts/build-release.sh, do not hand-edit.
// It fills the binaryTarget url (the GitHub Release asset for the release tag) and the
// checksum (swift package compute-checksum HiPayPayments.xcframework.zip).
//
// This mirrors the repository's Package.swift exactly EXCEPT the HiPayPayments target,
// which is a *remote* binaryTarget(url:checksum:) instead of a local binaryTarget(path:).
// The Swift products, targets and the HiPayCard resources are unchanged — keep this file in step
// with Package.swift whenever a product or target is added, or the tag ships an incomplete package.
//
// This manifest exists ONLY on release tags: the branch keeps the local one so day-to-day
// development builds against the XCFramework on disk.
let package = Package(
    name: "HiPayPaymentsKMP",
    // Required for the HiPayCard localized .strings catalogs (story 5.2);
    // a device locale with no catalog falls back to EN.
    defaultLocalization: "en",
    platforms: [.iOS(.v15)],
    products: [
        // Headless SDK: payment orchestration, no UI.
        .library(name: "HiPayCore", targets: ["HiPayCore"]),
        // Card entry UI layer on top of HiPayCore.
        .library(name: "HiPayCard", targets: ["HiPayCard"]),
        // Apple Pay button + payment (PassKit), opt-in: a merchant who does not import this
        // links no PassKit code / Apple Pay API (modularity, Option A).
        .library(name: "HiPayApplePay", targets: ["HiPayApplePay"]),
    ],
    targets: [
        // KMP binary hosted as a GitHub Release asset; integrity pinned by checksum.
        .binaryTarget(
            name: "HiPayPayments",
            url: "https://github.com/hipay/hipay-payments-sdk-ios/releases/download/1.1.0/HiPayPayments.xcframework.zip",
            checksum: "d5997e46e8921a79d7f10647b8f9d47e9f703841e05a9911744d0a05c079e6ad"
        ),
        .target(
            name: "HiPayCore",
            dependencies: ["HiPayPayments"]
        ),
        .target(
            name: "HiPayCard",
            dependencies: ["HiPayCore"],
            // Card-network brand icons (neutral + Visa/MC/Amex/Maestro/BCMC/CB),
            // loaded via Image(_:bundle: .module).
            resources: [.process("Resources")]
        ),
        // Apple Pay: the native PassKit button + (later) the payment orchestration on top of
        // HiPayCore. PassKit is a weak-linked system framework; nothing here loads unless imported.
        .target(
            name: "HiPayApplePay",
            dependencies: ["HiPayCore"]
        ),
    ]
)
